### ISSUE TITLE
Stop copying the image to CF card at 87%. 

### ISSUE THREAD

**Issue by jyin999** [pcdshub/pcds-plc-image-generator#10]

**Comment by jyin999** [comment]
The image generation file works. But I failed to copy the generated files to CF card. I tried a couple of times. It stops at 87%.  Missing many system files and have to copy to CF card manually.

![image](https://user-images.githubusercontent.com/55111839/185678058-5aed1ef6-c144-48bb-b8f8-d2747981125f.png)

**Comment by klauer** [comment]
Hmm, I don't think this is the fault of the image generator. Is it worth trying a different CF card? A different card reader?

**Comment by jyin999** [comment]
You are right. It is the brand new CF card which has issue.  No problem on the other card.
